#!/usr/bin/perl -w

#$test = 30;
#print
#	"here is a list containing strings, (this on)",
#"numbers (",3.6,
##") and variables: ", $test,
#"\n";

#$mone;$mtwo;
#($mone, $mtwo)=(1,3);
#print(("heads", "shoulders","knees","toes")[$mone,$mtwo]);
#print"\n";

#print(1..10,"\n");
#print('a'..'z',"\n");

#print "counting up: ", (1 .. 20),"\n";
#print "counting down: ",(20 .. 1),"\n";
#print "counting down with reverse: ",reverse(1 .. 20),"\n";
#print "half the alphabet: ",('a'..'m'),"\n";
#print "other have with reverse ",reverse('m'..'z'),"\n";


@array = (1,2,3);
print "@array, \n";
print join(@array, "\n");


