#!/usr/bin/perl -w

$regexp = shift;
@dirs = <>;
@dirs = `find @dirs -print`;
chop @dirs;
@regfile = grep(-f && -T,@dirs);
foreach $line(@regfile){
        open(IN, "<$line");
        while(<IN>){
                if(/$regexp/){
                print "$line:$_";
                }
        }
}
        
